package by.bsuir.spp.controller.command;

public enum CommandName {
    DB_TEST,
    ADD_USER,
    LOAD_PACKAGES,
    DELETE_PACKAGE,
    ADD_PACKAGE,
    SELECT_PACKAGE,
    UPDATE_PACKAGE,
    LOAD_PASSPORTS,
    UPDATE_PASSPORT,
    ADD_PASSPORT,
    SELECT_PASSPORT,
    DELETE_PASSPORT,
    PREPARE_DATA_FOR_CREATION_USER,
    SELECT_USER,
    DELETE_USER,
    UPDATE_USER,
    LOAD_USERS
}
